version: '3'

services:
  app:
    image: phpswoole/swoole
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - 9501:9501
    volumes:
      - .:/var/www